import React from 'react';
import './DocumentViewer.css';

const DocumentViewer = ({ type, deal, onClose }) => {
  const handlePrint = () => {
    window.print();
  };

  const isInvoice = type === 'invoice';
  const today = new Date().toLocaleDateString();

  return (
    <div className="document-modal-overlay">
      <div className="document-modal-content glass-morphism">
        <div className="doc-tools noprint">
          <button className="doc-close-btn" onClick={onClose}>Close</button>
          <button className="doc-print-btn" onClick={handlePrint}>Download as PDF (Print)</button>
        </div>

        <div className="printable-document">
          <div className="doc-header">
            <div className="doc-logo">SS</div>
            <div className="doc-title-block">
              <h1>{isInvoice ? 'TAX INVOICE' : 'PARTNERSHIP AGREEMENT'}</h1>
              <p>ID: #{deal.id.toString().padStart(6, '0')}</p>
              <p>Date: {today}</p>
            </div>
          </div>

          <hr />

          <div className="doc-parties">
            <div className="party-block">
              <h3>FROM:</h3>
              <p><strong>{deal.sponsorName || 'Marketplace Sponsor'}</strong></p>
              <p>{deal.sponsor?.company_name || 'Corporate Partner'}</p>
              <p>{deal.sponsor?.email}</p>
            </div>
            <div className="party-block">
              <h3>TO:</h3>
              <p><strong>{deal.deal_type === 'sponsorship' ? deal.organizerName : deal.influencerName}</strong></p>
              <p>{deal.deal_type === 'sponsorship' ? 'Event Organizer' : 'Digital Creator'}</p>
            </div>
          </div>

          <div className="doc-body">
            {isInvoice ? (
                <>
                <table className="doc-table">
                  <thead>
                    <tr>
                      <th>Description</th>
                      <th>Qty</th>
                      <th>Unit Price</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <strong>{deal.event?.title || deal.campaign?.title}</strong><br />
                        Sponsorship & Marketing Services
                      </td>
                      <td>1</td>
                      <td>{deal.payment_amount} {deal.currency}</td>
                      <td>{deal.payment_amount} {deal.currency}</td>
                    </tr>
                  </tbody>
                </table>
                <div className="doc-totals">
                    <p>Subtotal: {deal.payment_amount} {deal.currency}</p>
                    <p>GST/Tax (0%): 0.00 {deal.currency}</p>
                    <h2 className="grand-total">Total Paid: {deal.payment_amount} {deal.currency}</h2>
                </div>
                </>
            ) : (
                <div className="agreement-text">
                    <p>This agreement (the "Agreement") is entered into as of {today}, by and between <strong>{deal.sponsorName}</strong> and <strong>{deal.deal_type === 'sponsorship' ? deal.organizerName : deal.influencerName}</strong>.</p>
                    
                    <h4>1. PURPOSE</h4>
                    <p>The parties agree to collaborate on the project known as "{deal.event?.title || deal.campaign?.title}".</p>

                    <h4>2. COMPENSATION</h4>
                    <p>Sponsor agrees to pay the sum of {deal.payment_amount} {deal.currency} in exchange for specific deliverables and marketing rights defined in the project brief.</p>

                    <h4>3. DELIVERABLES</h4>
                    <p>The Recipient agrees to provide proof of work and visibility as agreed upon throughout the project duration.</p>

                    <h4>4. SIGNATURES</h4>
                    <div className="signatures-row">
                        <div className="sig-box">
                            <p>Signed by Sponsor:</p>
                            <div className="digital-sig">{deal.sponsorName}</div>
                            <span>Digitally Verified</span>
                        </div>
                        <div className="sig-box">
                            <p>Signed by Recipient:</p>
                            <div className="digital-sig">{deal.deal_type === 'sponsorship' ? deal.organizerName : deal.influencerName}</div>
                            <span>Digitally Verified</span>
                        </div>
                    </div>
                </div>
            )}
          </div>

          <div className="doc-footer">
            <p>Generated by Sponsorship Hub. This is a computer-generated document and is legally binding if signed by both parties.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentViewer;
