export const mapEventData = (event) => ({
  id: event.id,
  title: event.title,
  state: event.state,
  city: event.city || event.location,
  budget: Number(event.raw_budget) || 0,
  currency: event.currency || "INR",
  organizer_id: Number(event.organizer_id),
  description: event.description || "",
  about: event.about || "",
  category: event.category || "General",
  expected_audience: event.expected_audience || "",
  location: event.location || "",
  date: event.date || null,
  media_items: Array.isArray(event.media_items) ? event.media_items : [],
});

export const mapDealData = (deal, currentUser) => ({
  ...deal,
  sponsorId: deal.sponsor_id,
  organizerId: deal.organizer_id,
  influencerId: deal.influencer_id,
  campaignId: deal.campaign_id,
  eventId: deal.event_id,
  sponsorName: deal.sponsor_name || deal.sponsor?.full_name || "Sponsor",
  organizerName: deal.organizer_name || deal.organizer?.full_name || "Organizer",
  influencerName: deal.influencer_name || deal.influencer?.full_name || "Influencer",
  paymentAmount: deal.payment_amount,
  paymentDone: deal.payment_done,
  organizerAccepted: deal.organizer_accepted,
  sponsorAccepted: deal.sponsor_accepted,
  influencerAccepted: deal.influencer_accepted,
  organizerSigned: deal.organizer_signed,
  sponsorSigned: deal.sponsor_signed,
  influencerSigned: deal.influencer_signed,
  organizerSignature: deal.organizer_signature,
  sponsorSignature: deal.sponsor_signature,
  influencerSignature: deal.influencer_signature,
  organizerSignedAt: deal.organizer_signed_at,
  sponsorSignedAt: deal.sponsor_signed_at,
  influencerSignedAt: deal.influencer_signed_at,
});
